huh_encore:
  js_entries:
    - name: "contao-isotope-resource-booking-bundle"
      file: "vendor/heimrichhannot/contao-isotope-resource-booking-bundle/assets/js/contao-isotope-resource-booking-bundle.js"