services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  HeimrichHannot\IsotopeResourceBookingBundle\Attribute\BookingAttribute:
    public: true

  HeimrichHannot\IsotopeResourceBookingBundle\:
    resource: "../src/{DataContainer,EventListener}/*"
    public: true