services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $urlGenerator: '@contao.routing.url_generator'

  HeimrichHannot\IsotopeResourceBookingBundle\Attribute\BookingAttribute:
    public: true

  HeimrichHannot\IsotopeResourceBookingBundle\:
    resource: "../src/{Action,DataContainer,EventListener}/*"
    public: true