services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $urlGenerator: '@contao.routing.url_generator'

  HeimrichHannot\IsotopeResourceBookingBundle\:
    resource: "../src/{Action,Attribute,Controller,DataContainer,EventListener}/*"
    public: true